### ISSUE TITLE
RegisterTypeExtension Interface is not recognized

### ISSUE THREAD

**Issue by q349980363** [neolithos/neolua#107]
NeoLua Version:

Example to reproduce:
```Lua
  local dtList = doc.QuerySelectorAll("#list > dl > dt");
    local dt = dtList[1];
    dt.Index();
```
RegisterTypeExtension Interface is not recognized

![image](https://user-images.githubusercontent.com/4111244/71543987-74e15d00-29b4-11ea-9838-3b8194c85029.png)
![image](https://user-images.githubusercontent.com/4111244/71543996-790d7a80-29b4-11ea-8735-3ec30e52f380.png)

**Comment by q349980363** [comment]
I had a problem using AngleSharp.

**Comment by neolithos** [comment]
The problem is the following definition.

https://github.com/AngleSharp/AngleSharp/blob/532b5c1b1b77134e45b649c6f9e4033e083f1014/src/AngleSharp/Dom/NodeExtensions.cs#L616-L617

```C#
public static T Text<T>(this T nodes, String text)
    where T : IEnumerable<INode>
```
NeoLua can not assign generic type parameter to a type. The error message was a little misleading.

The fix, skips such methods.
