### ISSUE TITLE
Visual Basic reference example

### ISSUE THREAD

**Issue by khanduras** [neolithos/neolua#15]
Does anyone have a reference example for Visual Basic, using Option Explicit On and Option Strict On ?

**Comment by neolithos** [comment]
I installed VB (*yippie*). What is your exact problem?

**Comment by khanduras** [comment]
1. I couldn't implement Lua with Option Explicit On and Option Strict On by converting references from C# to VB.net.
2. I couldn't find a VB.net reference example by searching online.
3. I decided to install IronPython and was able to implement that with references from C#.
4. If you have a reference for VB.net implementing NeoLua with Option Explicit On and Option Strict On, I'm sure others would find it useful also.

**Comment by neolithos** [comment]
I did a "short" test:

first with strict on:
https://github.com/neolithos/neolua/blob/master/VBtest/Module1.vb
All is fine.

secound with strict off:
https://github.com/neolithos/neolua/blob/master/VBtest/Module2.vb
It is NOT working. VB calls always InvokeMember instead of get member.

My last VB is 15 years old (and it was called VB6 or so). It seems, that someone should add a test library, that does the following tests:
- get member
- set member
- get index
- set index
- Invoke member
- Invoke variable
- convert
- unary operations (e.g. -- ++)
- binary operations (e.g. + - / *)
After this I can check out for each operation, what is different.

I am not an expert on VB.NET, so I can not do it (it took me to long for this couple of lines).

It would be nice, if someone with more expirence do it?
The project name should be "NeoLua.TestVB".

**Comment by PatrickKursawe** [comment]
Hi there,

could you maybe extend this bullet list be referring to the tests you already did in C#? Like
“Invoke member -> CodePlexExample3a” or something like that?
Thank you!

Patrick

Von: neolithos [mailto:notifications@github.com]
Gesendet: Freitag, 16. Oktober 2015 19:14
An: neolithos/neolua <neolua@noreply.github.com>
Betreff: Re: [neolua] Visual Basic reference example (#15)


I did a "short" test:

first with strict on:
https://github.com/neolithos/neolua/blob/master/VBtest/Module1.vb
All is fine.

secound with strict off:
https://github.com/neolithos/neolua/blob/master/VBtest/Module2.vb
It is NOT working. VB calls always InvokeMember instead of get member.

My last VB is 15 years old (and it was called VB6 or so). It seems, that someone should add a test library, that does the following tests:

  *   get member
  *   set member
  *   get index
  *   set index
  *   Invoke member
  *   Invoke variable
  *   convert
  *   unary operations (e.g. -- ++)
  *   binary operations (e.g. + - / *) After this I can check out for each operation, what is different.

I am not an expert on VB.NET, so I can not do it (it took me to long for this couple of lines).

It would be nice, if someone with more expirence do it?
The project name should be "NeoLua.TestVB".

**Comment by pyrostrex** [comment]
@neolithos, if you are talking about the dochunk, In vb, I had to use DirectCast in order to use the correct DoChunk.

```vb.net
DirectCast(g, LuaGlobal).DoChunk("Scripts\Script.lua")
```

Not a vb.net expert so this will do. :stuck_out_tongue_closed_eyes:

Owh and also `Option Strict Off` was never needed since vb.net will always support late binding on Object type.

**Comment by neolithos** [comment]
@PatrickKursawe:
If I do the code example 3a with the current library, it will look bad. It would be a good ideas to fix the issues first.
@pyrostrex:
I did not know this command. So you are more a expert ;)

Is there a VB.NET expert somewhere?

**Comment by neolithos** [comment]
The commit 91181eee5702dfdd5c12233d2cfabbf4909b7aa4 should improve the combatibility with VB.

Can someone check this?
There is also a beta-version on nuget.
