### ISSUE TITLE
Syntax parser bug?

### ISSUE THREAD

**Issue by hdkeeper** [neolithos/neolua#19]
Possibly I've run into a bug in the syntax parser.

```lua
clr.System.Windows.Forms.MessageBox.Show( "Hello":ToUpper() );
-- Raises execption
```

Let's add extra parentheses.

```lua
clr.System.Windows.Forms.MessageBox.Show( ("Hello":ToUpper()) );
-- Works fine
```

**Comment by neolithos** [comment]
This is more issue of "finding the correct overloads".

I rewrote the whole stuff in the current beta, So, which version did you use?

**Comment by hdkeeper** [comment]
I've tested it with NeoLua release 1.1.0.

**Comment by hdkeeper** [comment]
It becomes really funny, I've switched to NamedArgument branch of NeoLua. Now it fails on following code.

```lua
clr.System.Windows.Forms.MessageBox.Show( string.gsub("192.168.33.15", '[0-9]+', "x") );
-- Throws exception
```

Paretheses fix it again.
```lua
clr.System.Windows.Forms.MessageBox.Show( (string.gsub("192.168.33.15", '[0-9]+', "x")) );
-- Works fine
```

**Comment by neolithos** [comment]
This time it is correct. Because, gsub returns a unknown number of objects (aka LuaResult). So, NeoLua will see something like this:

```
LuaResult r = string.gsub("192.168.33.15", '[0-9]+', "x");
CallDynamic("System.Windows.Forms.MessageBox.Show", r);
```

One rule in Lua is, that the last argument has to spread out to the maximum number of parameters, That is the reason for the choosen method. That rule is not so nice, if you have to deal with overloads.

Your second example does something like this:
```
object r = string.gsub("192.168.33.15", '[0-9]+', "x");
CallDynamic("System.Windows.Forms.MessageBox.Show", r);
```

But you can also write (how I do it):
```
clr.System.Windows.Forms.MessageBox.Show(cast(string, string.gsub("129.12.12.4", "[0-9]+", "x")));
```
even better
```
clr.System.Windows.Forms.MessageBox:Show(cast(string, string.gsub("129.12.12.4", "[0-9]+", "x")));
```

This should work, but didn't, I will fix this:
```
clr.System.Windows.Forms.MessageBox.Show[clr.System.String](string.gsub("129.12.12.4", "[0-9]+", "x"));
```

**Comment by hdkeeper** [comment]
Okay, I've got the point. Thanks for explanations.

**Comment by neolithos** [comment]
Cool, with the named parameters it looks even better:
```
 clr.System.Windows.Forms.MessageBox:Show(text=string.gsub("1.2.4.5", "[0-9]+", "x"))
```
