### ISSUE TITLE
Sandboxing Lua code.

### ISSUE THREAD

**Issue by orthoxerox** [neolithos/neolua#2]
I want to run Lua code in a mostly empty environment, so my scripts do not have access to IO, for example.

My first attempt was to clear the members of the default LuaGlobal, but I got:

```
Can't load file LuaTable.cs under c:\Projects\NeoLua\NeoLua.
Check the file permission and the existence of that file.

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Neo.IronLua.LuaTable.RemoveValue(Int32 iIndex) in c:\Projects\NeoLua\NeoLua\LuaTable.cs:line 1581
   at Neo.IronLua.LuaTable.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.Clear()
```

It looks like two problems at the very least: you have debug info in the NuGet version of the library, so SharpDevelop tried to open the source, and second, you can't run LuaGlobal.Members.Clear() despite .IsReadOnly being set to false.

The third problem is that the environment doesn't contain the "clr" member, but I am still able to use it:
    assert: System.Object LuaAssert(System.Object, System.String)
    collectgarbage: Neo.IronLua.LuaResult LuaCollectgarbage(System.String, System.Object)
    dofile: Neo.IronLua.LuaResult LuaDoFile(System.Object[])
    dochunk: Neo.IronLua.LuaResult LuaDoChunk(System.Object[])
    error: Void LuaError(System.String, Int32)
    getmetatable: Neo.IronLua.LuaTable LuaGetMetaTable(System.Object)
    ipairs: Neo.IronLua.LuaResult LuaIPairs(Neo.IronLua.LuaTable)
    pairs: Neo.IronLua.LuaResult LuaPairs(Neo.IronLua.LuaTable)
    load: System.Object LuaLoad(System.Object, System.String, System.String, Neo.IronLua.LuaTable)
    loadfile: System.Object LuaLoadFile(System.String, System.String, Neo.IronLua.LuaTable)
    next: System.Object LuaNext(Neo.IronLua.LuaTable, System.Object)
    pcall: Neo.IronLua.LuaResult LuaPCall(System.Object, System.Object[])
    print: Void LuaPrint(System.Object[])
    rawequal: Boolean LuaRawEqual(System.Object, System.Object)
    rawget: System.Object LuaRawGet(Neo.IronLua.LuaTable, System.Object)
    rawlen: Int32 LuaRawLen(System.Object)
    rawset: Neo.IronLua.LuaTable LuaRawSet(Neo.IronLua.LuaTable, System.Object, System.Object)
    require: Neo.IronLua.LuaResult LuaRequire(System.Object)
    select: Neo.IronLua.LuaResult LuaSelect(System.String, System.Object[])
    setmetatable: Neo.IronLua.LuaTable LuaSetMetaTable(Neo.IronLua.LuaTable, Neo.IronLua.LuaTable)
    tonumber: System.Object LuaToNumber(System.Object, System.Nullable`1[System.Int32])
    tostring: System.String LuaToString(System.Object)
    type: System.String LuaTypeTest(System.Object, Boolean)
    xpcall: Neo.IronLua.LuaResult LuaXPCall(System.Object, System.Object, System.Object[])
    _VERSION: NeoLua 5.3
    table: Neo.IronLua.LuaTable
    coroutine: Neo.IronLua.LuaThread
    io: Neo.IronLua.LuaFilePackage
    package: Neo.IronLua.LuaGlobal+LuaLibraryPackage
    bit32: Neo.IronLua.LuaLibraryBit32
    math: Neo.IronLua.LuaLibraryMath
    os: Neo.IronLua.LuaLibraryOS
    string: Neo.IronLua.LuaLibraryString
    debug: Neo.IronLua.LuaLibraryDebug

Even a lambda that is created without an environment still has access to everything in "clr". Is there a way to run NeoLua code in a tighly sandboxed environment? Creating a sandbox within a chunk doesn't help either:

```
//this doesn't work...
g.DoChunk("do\r\n" +
          "local chunk = \""+ chunk +"\"\r\n" + //ouch, injection risk in sample code!
          "load(chunk,chunk,'t',{})()\r\n" +
          "end", "test3");
//nor this...
g.DoChunk("_ENV = {}\r\n" + chunk, "test4");
```

**Comment by neolithos** [comment]
I added Sandboxing functionality to the package.

Let me know what I forgot.

**Comment by orthoxerox** [comment]
If I got the idea right, I have to put my additional types into my new environment type and then do this:

```csharp
    var opts = new LuaCompileOptions();
    opts.DynamicSandbox = (x) =>
    {
        if (x == env.Members["print"]) return x;
        if (x == env.Members["pairs"]) return x;
        //and so on
        return null;
    };
```

and compile my chunk with this sandbox.

I have a few questions now.

1. It looks like the result is not cached, my lambda is called every time I print something. Have you measured the performance hit? It is invoked even for globals created by the script itself (but is not invoked for _G). Globals are bad, of course, but I am not sure if that was intended.

2. Is there a way to simplify the check? I don't want to mention every single member in my environment, I just want to limit access to, for example, System and all other namespaces I have referenced in my project.

**Comment by neolithos** [comment]
Mmmh, that was not what I have in mind.

At first, it is possible to create your own Lua environment. Just inherit it from LuaTable. But this has nothing to do with the sandboxing.

Sandboxing mean that every *get* will be controlled. I hope, I have catched every instruction.

### Background

I choose this approach, because in a dynamic language you never know, what will be returned if you write t.a (first reason).
Example:
    clr.MyNamespace.MyType -> may be return a LuaType, that represents a namespace, but after you load the a assembly the same line can return a  type.

So, every call must be checked.

Now, you can mention, I can check for example in LuaType, what type should be returned, and also for LuaTable. This is true, but I can not introduce this check for e.g. IronPython or other dynamic libraries (second reason).

### How it works

LuaCompileOptions are the key for the sandboxing. And there are tree levels on which you can interfere the mechanism.

#### Easiest

Set DynamicSandbox, every value that is processed by the script will be passed throw this function. It can be manipulate or throw an exception. This is the slowest why to do sandboxing.

#### Type based filter

It is possible to inherit from **LuaCompileOptions**  and you can override **Sandbox**.
Sandbox desides, what should be done with the result of the expression.
* None: Do not inject the DynamicSandbox call
* Reject: Create a exception (see RestrictAccess)
* Dynamic: Call DynamicSandbox

#### Expression based filter

This is the lowest point, **SandboxCore**. Desid on the current position in the parse process, what should be done.
At this point it is also possible to inject much faster implementation of a sandboxing algorithm.
For example something like this:
```
static CallSite c = new CallSite()
c.execute(a);

c.execute =(a) =>
{
  if a typeis Type
    return a;
  else
    execute = UpdateExpression(a);
}
```

### What will be come next

I will make the clr-Module exchangable, that everyone can add there own implemention. This will allow to add a filter only on the types. But, this step needs some investigations


I hope I could clearfy this a little bit.
