### ISSUE TITLE
[documentation request] Xamarin.iOS support

### ISSUE THREAD

**Issue by eropple** [neolithos/neolua#33]
Hey there! Just saw NeoLua and I'm very interested in exploring it further. I'm currently without access to a working Xamarin.iOS environment, otherwise I'd check this myself, but I noticed that NeoLua uses the DLR but advertises support for iOS. I wasn't aware that this is possible; could you perhaps explain that a little bit? (My understanding is that the DLR is wholly incompatible with Xamarin.iOS; maybe a line in the README to explain the NeoLua support for it would clear things up?)

Thanks very much! NeoLua looks really cool and I can't wait to play with it.

**Comment by neolithos** [comment]
Because, I have no iOS devices or development tools. I just followed the development documentations.

I tested:
- Desktop > All is ok :D
- Mono under Fedora and Gentoo > All is ok
- Mono under MIPS > issues with complex datatypes > nobody will fix it > deep in the core of IL-Assembler
- UWP (.net core 5) > issues with the dynamic compilation, only on ARM-Devices > should be solved soon, the issue I created is closed with positive feedback. I need to test again.

It would be nice to get feedback.

**Comment by ddotlic** [comment]
Here's some feedback - despite the hopes of this working (I'll explain why it _could_ work) it's actually not and the way it fails is rather weird.

BTW, you don't need iOS device but you do need a macOS (whether 'Hackintosh' or an actual Mac, I used MacBook Pro for testing).

Running the example code provided in your readme file partially works to a point and then the Xamarin debugger just skips the lines of code (??!) without doing anything. Most of the time there were no exceptions whatsoever. I did get **one** exception **once** which alluded to the unsupported operation. As the original poster asked, officially DLR is not supported by Xamarin.iOS because at some point the IL is emitted and compiled, which Apple forbids.

_However_ the reason I hoped it **might** work is because there's actually a Linq Expression _interpreter_ included with DLR which is supposed to be used for the first N runs (reportedly N is configurable) so at least for simple test cases and first few runs the interpreter should work just fine.

It doesn't in case of NeoLua, which is a shame...

For completeness, I tested the same example code on Android and as expected it works like a charm.

I think you should remove the Xamarin.iOS support from the readme, it might confuse people 😞

**Comment by neolithos** [comment]
Thanks for the testing.
I hope that I will find some time to check, what I can do.
