### ISSUE TITLE
about "..."

### ISSUE THREAD

**Issue by xiaomiaozone** [neolithos/neolua#52]
Hi, I found two problems when I used it.
```lua
function test1(...)
	print(...[1]) -- print 2 ???
end

test1(1,2,3,4,5)
  
```

```lua
function test2(...)
	local t={...}	-- error in CompileChunk
	print(t[1])
end

test2(1,2,3,4,5)
  
```

Thanks for you help :)

**Comment by neolithos** [comment]
Hi,
the first example is not defined in lua. In c-lua you get the error `"input:2: ')' expected near '['` (https://www.lua.org/cgi-bin/demo).
The code only compiles, because I take the `...` as an special array variable (of the type `LuaResult`). `LuaResult` has an indexer, and this indexer is zero based (as every indexer in .net). E.g. if you create an array/list/..., you see the same zero based index. 
**Only** LuaTable is one based.

The second code example compiles fine in NeoLua 1.2.20 and printes the expected result `1`. What is your version?

**Comment by xiaomiaozone** [comment]
Thanks, The second code is my problem. I solved it by add `InternalsVisibleToAttribute`.  :)
