### ISSUE TITLE
string.find vs s:find

### ISSUE THREAD

**Issue by tschmit** [neolithos/neolua#8]
hello in the following code:

    var v = new {
        F1Article = "HON",
        CArticle = "TRADUCTION",
        IsCpi = "X",
        HT = 10
    };
    using (Lua le = new Lua()) {
        LuaGlobal lg = le.CreateEnvironment();                                

        try {
            Func<Object, Boolean> f0 = lg.Lua.CreateLambda<Func<Object, Boolean>>(String.Format("f0"), "return l.CArticle:find(\"^TRAD\")", "l");
            Console.WriteLine("f0: {0}", f0(v));
        } catch (Exception ex) { 
            Console.WriteLine(ex.Message); 
        }

        try {
            Func<Object, Boolean> f1 = lg.Lua.CreateLambda<Func<Object, Boolean>>(String.Format("f1"), "return string.find(l.CArticle, \"^TRAD\")", "l");
            Console.WriteLine("f1: {0}", f1(v));
        } catch (Exception ex) {
            Console.WriteLine(ex.Message);
        }
    }

the first try runs, but the second crashes.

**Comment by neolithos** [comment]
Hello,

your are using the lambda compiler.

This compiler does not generate any access to the environment, what the normal compile chunk does. The normal lua packages are part of the LuaGlobal ([see documentation](https://github.com/neolithos/neolua/blob/master/doc/04_02_engine.md#createlambda)).

The first example uses the type extension and not the package, that is the reason why it runs successful.

Btw. there is no need of creating a Environment, because it is never used in your code.

```C#
using (Lua le = new Lua()) 
{
        Func<Object, Boolean> f0 = le.CreateLambda<Func<Object, Boolean>>("f0", "return l.CArticle:find(\"^TRAD\")", "l");
        Console.WriteLine("f0: {0}", f0(v));
}
```

**Comment by tschmit** [comment]
hello,

thank you. My mistake.

Highlighting " It is not possible" in the documentation may be a good idea
and illustrating it with my mistake"

thank you again, very nice code

thierry

2015-04-07 23:07 GMT+02:00 neolithos <notifications@github.com>:
