### ISSUE TITLE
Why need name while calling DoChunk?

### ISSUE THREAD

**Issue by zhangjiejia** [neolithos/neolua#98]
Can someone tell me, why need name while calling DoChunk?

**Comment by neolithos** [comment]
The name is used for the debug information.

**Comment by zhangjiejia** [comment]
Thanks, but when I use a empty string, it throw io exception, why?

**Comment by neolithos** [comment]
Because I test in the most cases for `String.IsNullOrEmpty`.

The name is imported for the debug information, but it could also be a place holder like `unknown.lua`.

PR is welcome, to set a dummy name if the name is empty.

**Comment by zhangjiejia** [comment]
So you mean that it will write debug info to harddisk? What if I don't need debug? I just run a small script like "return 1 + 1"

**Comment by neolithos** [comment]
Not to the harddisk, but into the memory. If you set the compile options to `null`, it will not generate debug information at all. But the current implementation enforces a name, because otherwise the exception will be more confusing.

For such short expression you should also investigate `CreateLambda`.

**Comment by zhangjiejia** [comment]
Thanks, I understand now
